name: Daily Quote

on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '20 20 * * *'
  workflow_dispatch: 

jobs:
  send-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          MY_NUMBER: ${{ secrets.MY_NUMBER }}
          API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}
        run: python main.py
